---
- name: Pull docker Image
  hosts: local
  connection: local
  tasks:
    - name: Pull junit devops image
      docker_image:
        name: advaitlonkar/scientific-calculator-with-devops
        source: pull
